In [6]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))
print(x3)
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)
print("x3 itemsiz:",x3.itemsize,"")
print("nbytes:",x3.nbytes,"bytes")

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 itemsiz: 4 
nbytes: 240 bytes


In [7]:
x2[1,3]=13

In [8]:
x2[1,3]


13

In [9]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8, 13],
       [ 1,  6,  7,  7]])

In [10]:
x2[1,3]=3.53

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 3],
       [1, 6, 7, 7]])

In [12]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 3],
       [1, 6, 7, 7]])

In [13]:
x3[1,2]

array([2, 0, 0, 4, 5])

In [14]:
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x1[1:3]

array([1, 2])

In [16]:
x1[:3]

array([0, 1, 2])

In [17]:
x1[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x1[::2]

array([0, 2, 4, 6, 8])

In [19]:
x1[1::2]

array([1, 3, 5, 7, 9])

In [20]:
x1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
x1[5::-2]

array([5, 3, 1])

In [22]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 3],
       [1, 6, 7, 7]])

In [23]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [3, 8, 6, 7],
       [4, 2, 5, 3]])

In [24]:
x2[1, ::1]

array([7, 6, 8, 3])

In [25]:
print(x2[:,0]) #first program

[3 7 1]


In [26]:
x2_sub=x2
x2_sub

array([[3, 5, 2, 4],
       [7, 6, 8, 3],
       [1, 6, 7, 7]])

In [27]:
x2_sub[0,0]=999
x2_sub

array([[999,   5,   2,   4],
       [  7,   6,   8,   3],
       [  1,   6,   7,   7]])

#putting numbers 1 through 9 in a 3*3 grid
grid=np.arange(1,10).reshape((3,3))
print(grid)

In [28]:
x=np.array([1,2,3])
x.reshape([1,3])

array([[1, 2, 3]])

In [29]:
x[np.newaxis,:] # adding new dimensions

array([[1, 2, 3]])

In [30]:
x[:,np.newaxis] #adding new dimesions

array([[1],
       [2],
       [3]])

In [31]:
#np.concatenate,np.vstack,np.hstack

x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [32]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


grid=np.arange(9).reshape(3,3)
print(grid)

In [33]:
x=np.array([1,2,3])
grid=np.array([[9,8,7,],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [34]:
y=np.array([[99],[99]])m
np.hstack([grid,y])

SyntaxError: invalid syntax (4078826388.py, line 1)

In [ ]:
x=[4,5,6,88,6,5,4,]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[4 5 6] [88  6] [5 4]


In [ ]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower= np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left,right=np.hsplit(grid,[2])
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [ ]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
with open("/content/sample_data/text",'a') as f:
  f.write("My First File\n")
  f.write("This is in file")

In [ ]:
with open("/content/sample_data/text",'w') as f:
  f.write("My First File\n")
  f.write("This is in file")

In [ ]:
with open("/content/sample_data/text",'r+') as f:
  xx=f.read(); #f.read(10)
  print(xx)

My First File
This is in fileMy First File
This is in file


In [ ]:
import csv
courses=[('OS',1,'Sep'),('DL',2,'Sep'),('Stat',3,'Sep')]
cf=open('student.csv','w',newline='')#write Mode
obj=csv.writer(cf)
for courses in courses:
  obj.writerow(courses) #writerow
cf.close

<function TextIOWrapper.close()>

In [ ]:
import csv
courses=[('PY',4,'Sep'),('C',5,'Sep')]
cf=open('student.csv','r',newline='')
obj=csv.writer(cf)
for courses in courses:
    obj.writerows(courses)
cf.close()

FileNotFoundError: [Errno 2] No such file or directory: 'student.csv'

In [ ]:
cf=open('student.csv','r',newline='')#read
obj=csv.reader(cf)
for row in obj:
  print(row)