In [2]:
#fancy indexing
import numpy as np
rand=np.random.RandomState(0)
x=rand.randint(100,size=10)
print(x)

[44 47 64 67 67  9 83 21 36 87]


In [3]:
[x[3],x[7],x[2]]

[67, 21, 64]

In [4]:
ind=[3,7,2,5]
x[ind]

array([67, 21, 64,  9])

In [5]:
ind=np.array([[3,7],[2,5]])
x[ind]

array([[67, 21],
       [64,  9]])

In [6]:
x=np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
row=np.array([0,1,2])
col=np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

In [8]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
x[2,[2,0,1]]

array([10,  8,  9])

In [10]:
#modify values with fancy indexing
x=np.arange(10)
i=np.array([2,1,5,8])
x[i]=56
print(x)

[ 0 56 56  3  4 56  6  7 56  9]


In [11]:
#sorting
x=np.array([2,1,3,4,9,5])
np.sort(x)

array([1, 2, 3, 4, 5, 9])

In [12]:
x.sort()
print(x)

[1 2 3 4 5 9]


In [13]:
x=np.array([2,1,3,4,9,5])
i=np.argsort(x)
print(i)

[1 0 2 3 5 4]


In [14]:
rand=np.random.RandomState(0)
x=rand.randint(0,10,(4,6))
print(x)

[[5 0 3 3 7 9]
 [3 5 2 4 7 6]
 [8 8 1 6 7 7]
 [8 1 5 9 8 9]]


In [15]:
np.sort(x,axis=0) #sort each column

array([[3, 0, 1, 3, 7, 6],
       [5, 1, 2, 4, 7, 7],
       [8, 5, 3, 6, 7, 9],
       [8, 8, 5, 9, 8, 9]])

In [16]:
np.sort(x,axis=1)

array([[0, 3, 3, 5, 7, 9],
       [2, 3, 4, 5, 6, 7],
       [1, 6, 7, 7, 8, 8],
       [1, 5, 8, 8, 9, 9]])

In [17]:
#partial sort
x=np.array([7,2,5,8,9,3,4,1])#partiton of elements according to positon
np.partition(x,3)

array([2, 3, 1, 4, 5, 7, 9, 8])

In [18]:
#structured arrays
name=['Aryan','Kevin','Alvis','Adithya']
age=[20,21,22,21]
weight=[48.0,51.0,57.0,63.0]

In [19]:
x=np.zeros(4,dtype=int)
x

array([0, 0, 0, 0])

In [20]:
data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})

In [21]:
data['name']=name
data['age']=age
data['weight']=weight
print(data)

[('Aryan', 20, 48.) ('Kevin', 21, 51.) ('Alvis', 22, 57.)
 ('Adithya', 21, 63.)]


In [22]:
#refering values by index or by name
print(data['name'])#getting all names
print(data[0])#first row of data

['Aryan' 'Kevin' 'Alvis' 'Adithya']
('Aryan', 20, 48.)


In [23]:
#referring values by index or by name
print(data['name'])#getting all names
print(data[0]) #first row of adata
print(data[-1]['name']) #getting the name from the last row

['Aryan' 'Kevin' 'Alvis' 'Adithya']
('Aryan', 20, 48.)
Adithya


In [24]:
data[data['age']<30]['name']

array(['Aryan', 'Kevin', 'Alvis', 'Adithya'], dtype='<U10')

In [25]:
#crating Structured arrays
np.dtype({'names':('name','age','weight'),'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [26]:
np.dtype({'names':('name','age','weight'),'formats':((np.str_,10),int,np.float32)})


dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [29]:
np.dtype([('name','S10'),('age','i4'),('weight','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])