In [1]:
import random
import numpy as np

new_out= random.randint(20,40)
print(new_out)

21


In [4]:
import numpy
arr = numpy.array([[11, 2, 66, 23, 21, 3],
                   [4, 5, 23, 31, 5, 16],
                   [7, 81, 22, 43, 45, 87],
                   [6, 8, 16, 3, 4, 5],
                   [2, 34, 88, 5, 9, 38],
                   [7, 4, 36, 43, 21, 6]])
max_element = numpy.max(arr)
min_element = numpy.min(arr)
print('maximum element in the array is:',
      max_element)
print('minimum element in the array is:',
      min_element)

maximum element in the array is: 88
minimum element in the array is: 2


In [15]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 1 1 1 1]
Second array:
[0 1 1 1 1 0]
False


In [25]:
import numpy as np
x = np.array([3, 2, 4, 6, 9, 12, 14, 16, 18, 21, 24, 27, 40, 42, 45, 48, 99, 100])
div3=x[x%3==0]#divisble by 3
print(div3)
div2=x[x%2!=0]#divisble by 2
print(div2)
div5=x[x%5==0]#divisble by 5
print(div5)
div35=x[(x%5==0) & (x%3==0)]#divisible by 3 and 5
print(div35)
x[x%5==0]=55
print(x)




[ 3  6  9 12 18 21 24 27 42 45 48 99]
[ 3  9 21 27 45 99]
[ 40  45 100]
[45]
[ 3  2  4  6  9 12 14 16 18 21 24 27 55 42 55 48 99 55]


In [13]:
import numpy as np
np.random.seed(0) 
x1=np.random.randint(10,size=6) 
x2=np.random.randint(10,size=(3,4)) 
x3=np.random.randint(10,size=(3,4,5))
print(x3) 


[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [27]:
import numpy as np
list = [2, 40, 2, 502, 177, 7, 9]
print(np.average(list))
print(np.var(list))
print(np.std(list))

105.57142857142857
29579.10204081633
171.98576115718512
